# Cities: Skylines 2 RL Agent Configuration

# Game Interface Settings
interface:
  type: "api"  # "api" or "vision"
  # API settings (if available)
  api:
    host: "localhost"
    port: 5000
    timeout: 30
  # Computer Vision settings (fallback)
  vision:
    capture_fps: 5
    screen_region: [0, 0, 1920, 1080]  # [x, y, width, height]
    ocr_confidence: 0.7

# Environment Settings
environment:
  observation_space:
    include_visual: true
    image_size: [84, 84]  # Height, Width
    grayscale: false
    include_metrics: true
    metrics:
      - "population"
      - "happiness"
      - "traffic_flow"
      - "budget_balance"
      - "pollution"
      - "land_value"
  action_space:
    # Zoning actions
    zone:
      - "residential"
      - "commercial"
      - "industrial"
      - "office"
    # Infrastructure actions
    infrastructure:
      - "road_straight"
      - "road_curve"
      - "highway"
      - "public_transport"
      - "power"
      - "water"
    # Budget actions
    budget:
      - "increase_residential_budget"
      - "decrease_residential_budget"
      - "increase_commercial_budget"
      - "decrease_commercial_budget"
      - "increase_industrial_budget"
      - "decrease_industrial_budget"
      - "increase_transport_budget"
      - "decrease_transport_budget"
  reward:
    # Components and their weights in the reward function
    population_growth: 1.0
    happiness: 2.0
    budget_balance: 1.5
    traffic_flow: 1.0
    pollution_penalty: -1.0
    bankruptcy_penalty: -10.0
  time_scale: 3  # Game speed (1-3)
  max_episode_steps: 1000

# Agent Settings
agent:
  algorithm: "PPO"  # "PPO", "DQN", "A2C"
  # PPO specific settings
  ppo:
    n_steps: 512
    batch_size: 64
    n_epochs: 10
    gamma: 0.99
    gae_lambda: 0.95
    clip_range: 0.2
    learning_rate: 0.0003
    ent_coef: 0.01
    vf_coef: 0.5
    max_grad_norm: 0.5
  # DQN specific settings
  dqn:
    buffer_size: 100000
    learning_starts: 1000
    batch_size: 32
    gamma: 0.99
    tau: 1.0
    train_freq: 4
    target_update_interval: 1000
    exploration_fraction: 0.1
    exploration_final_eps: 0.05
  # Neural Network Architecture
  network:
    cnn:
      filters: [32, 64, 64]
      kernel_sizes: [8, 4, 3]
      strides: [4, 2, 1]
    mlp:
      hidden_layers: [256, 128]
    use_lstm: false
    lstm_units: 128

# Training Settings
training:
  total_timesteps: 1000000
  eval_freq: 10000
  n_eval_episodes: 5
  save_freq: 50000
  log_interval: 1000
  random_seed: 42
  n_envs: 1  # Number of parallel environments

# Paths
paths:
  logs: "../logs"
  models: "../models"
  data: "../data"
  tensorboard: "../logs/tensorboard" 