experiment_name: fully_autonomous_cs2_agent
seed: 42
paths:
  log_dir: logs/autonomous
  model_dir: models/autonomous
  tensorboard_dir: tensorboard/autonomous
interface:
  type: auto_vision
  detection_method: ocr
  ocr_confidence: 0.6
  template_threshold: 0.7
  cache_detections: true
  vision:
    screen_region: [0, 0, 1920, 1080]
environment:
  type: cs2
  observation_space:
    type: combined
    include_visual: true
    include_metrics: true
    image_size: [84, 84]
    grayscale: true
    normalize_metrics: true
    metrics: [population, happiness, budget_balance, traffic]
  action_space:
    type: advanced
    zone: [residential, commercial, industrial, office, delete_zone]
    infrastructure: [road, power_line, water_pipe, park, service_building, delete_infrastructure]
    budget: [increase_residential_tax, decrease_residential_tax, increase_commercial_tax, decrease_commercial_tax, increase_industrial_tax, decrease_industrial_tax, increase_service_budget, decrease_service_budget]
  reward_function:
    type: balanced
    weights:
      population: 0.3
      happiness: 0.2
      budget: 0.2
      traffic: 0.2
      discovery: 0.1
  max_episode_steps: 2000
  metrics_update_freq: 10
exploration:
  frequency: 0.3
  random_action_frequency: 0.2
  menu_buffer_size: 50
training:
  total_timesteps: 10000000
  checkpoint_freq: 100000
  evaluate_during_training: true
  eval_freq: 100000
  n_envs: 1
agent:
  policy_type: MultiInputPolicy
  learning_rate: 3e-4
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  use_sde: false
